version: '3'
services:
  govf:
    image: 192.168.1.2:5000/vf
    container_name: videofetcher
    volumes:
      -  ./configs:/govf/configs
    restart: always

  api:
    image: 192.168.1.2:5000/dlapi
    container_name: ytdlpapi
    restart: always