version: '2'
services:
  govf:
    image: vf
    container_name: videofetcher
    build: 
      context: ./
      dockerfile: docker/Dockerfile.arm
    volumes:
      -  ./configs:/govf/configs
    environment:
      - http_proxy=http://172.30.1.5:3128
      - https_proxy=http://172.30.1.5:3128