version: '2'
services:
  govf:
    image: vf
    container_name: videofetcher
    platform: arm64
    build: 
      context: ./
      dockerfile: docker/Dockerfile.arm64
    volumes:
      -  ./configs:/govf/configs